package view;

import controller.InicialController;
import javax.swing.JDesktopPane;

public class JFrameInicial extends javax.swing.JFrame {

    private final InicialController inicialController;
    
    public JFrameInicial() {
        this.inicialController = new InicialController(this);
        
        initComponents();
        
        encerrarItemMenu.addActionListener(inicialController);
        
        cadastroPessoaItemMenu.addActionListener(inicialController);
        cadastroSalaEventoItemMenu.addActionListener(inicialController);
        cadastroEspacoCafeItemMenu.addActionListener(inicialController);
        
        consultaPessoaItemMenu.addActionListener(inicialController);
        consultaSalaEventoItemMenu.addActionListener(inicialController);
        consultaEspacoCafeItemMenu.addActionListener(inicialController);
    }

    public JDesktopPane getDesktopPane()
    {
        return desktopPanelPrincipal;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        encerrarItemMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        cadastroPessoaItemMenu = new javax.swing.JMenuItem();
        cadastroSalaEventoItemMenu = new javax.swing.JMenuItem();
        cadastroEspacoCafeItemMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        consultaPessoaItemMenu = new javax.swing.JMenuItem();
        consultaSalaEventoItemMenu = new javax.swing.JMenuItem();
        consultaEspacoCafeItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela inicial");

        javax.swing.GroupLayout desktopPanelPrincipalLayout = new javax.swing.GroupLayout(desktopPanelPrincipal);
        desktopPanelPrincipal.setLayout(desktopPanelPrincipalLayout);
        desktopPanelPrincipalLayout.setHorizontalGroup(
            desktopPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPanelPrincipalLayout.setVerticalGroup(
            desktopPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu3.setText("Opções");

        encerrarItemMenu.setText("Encerrar programa");
        jMenu3.add(encerrarItemMenu);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cadastros");

        cadastroPessoaItemMenu.setText("Pessoa");
        cadastroPessoaItemMenu.setActionCommand("Cadastro Pessoa");
        jMenu1.add(cadastroPessoaItemMenu);

        cadastroSalaEventoItemMenu.setText("Sala de evento");
        cadastroSalaEventoItemMenu.setActionCommand("Cadastro Sala Evento");
        jMenu1.add(cadastroSalaEventoItemMenu);

        cadastroEspacoCafeItemMenu.setText("Espaço café");
        cadastroEspacoCafeItemMenu.setActionCommand("Cadastro Espaço Café");
        jMenu1.add(cadastroEspacoCafeItemMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        consultaPessoaItemMenu.setText("Pessoa");
        consultaPessoaItemMenu.setActionCommand("Consulta Pessoa");
        jMenu2.add(consultaPessoaItemMenu);

        consultaSalaEventoItemMenu.setText("Sala de evento");
        consultaSalaEventoItemMenu.setActionCommand("Consulta Sala Evento");
        jMenu2.add(consultaSalaEventoItemMenu);

        consultaEspacoCafeItemMenu.setText("Espaço café");
        consultaEspacoCafeItemMenu.setActionCommand("Consulta Espaço Café");
        jMenu2.add(consultaEspacoCafeItemMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanelPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanelPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroEspacoCafeItemMenu;
    private javax.swing.JMenuItem cadastroPessoaItemMenu;
    private javax.swing.JMenuItem cadastroSalaEventoItemMenu;
    private javax.swing.JMenuItem consultaEspacoCafeItemMenu;
    private javax.swing.JMenuItem consultaPessoaItemMenu;
    private javax.swing.JMenuItem consultaSalaEventoItemMenu;
    private javax.swing.JDesktopPane desktopPanelPrincipal;
    private javax.swing.JMenuItem encerrarItemMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
