package view;

import controller.EspacoCafeController;
import model.entity.Espaco;

public class JInternalFrameCadastroEspacoCafe extends javax.swing.JInternalFrame {

    private final EspacoCafeController espacoCafeController;
    
    public JInternalFrameCadastroEspacoCafe() {
        espacoCafeController = new EspacoCafeController(this);
        
        initComponents();
        
        cancelarButton.addActionListener(espacoCafeController);
        salvarButton.addActionListener(espacoCafeController);
    }
    
    public Espaco getEspaco() throws Exception
    {
        Espaco espaco = new Espaco();
        
        espaco.setNome(cadastroNomeEspaco.getText());
        espaco.setLotacao((Integer) cadastroLotacao.getValue());
        
        return espaco;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cadastroNomeEspaco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cadastroLotacao = new javax.swing.JSpinner();
        cancelarButton = new javax.swing.JButton();
        salvarButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de espaço café");
        setPreferredSize(new java.awt.Dimension(386, 217));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cadastro de espaço café");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        getContentPane().add(cadastroNomeEspaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 320, -1));

        jLabel3.setText("Lotação");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        getContentPane().add(cadastroLotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 310, -1));

        cancelarButton.setText("Cancelar");
        getContentPane().add(cancelarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        salvarButton.setText("Salvar");
        getContentPane().add(salvarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cadastroLotacao;
    private javax.swing.JTextField cadastroNomeEspaco;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton salvarButton;
    // End of variables declaration//GEN-END:variables
}
