package view;

import controller.PessoaController;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.entity.Etapa;
import model.entity.Pessoa;

public class JInternalFrameConsultaPessoa extends javax.swing.JInternalFrame {

    private final PessoaController pessoaController;
    
    private List<Pessoa> listPessoas;
    
    public JInternalFrameConsultaPessoa() {
        initComponents();
        
        pessoaController = new PessoaController(this);
        
        consultaFechar.addActionListener(pessoaController);
        
        tabelaPessoas.getSelectionModel().addListSelectionListener(pessoaController);
    }
    
    public JTable getTable()
    {
        return tabelaPessoas;
    }
    
    public void setPessoas(List<Pessoa> listPessoas)
    {
        this.listPessoas = listPessoas;
        
        DefaultTableModel dtm = (DefaultTableModel) tabelaPessoas.getModel();
        dtm.setRowCount(0);
        
        for (Pessoa pessoa : this.listPessoas)
        {
            Object[] objPessoa = {pessoa.getNome(), pessoa.getSobrenome()};
            dtm.addRow(objPessoa);
        }
    }
    
    public Pessoa getPessoaSelecionada(int selected)
    {
        return listPessoas.get(selected);
    }
    
    public void setPessoaSelecionada(Pessoa pessoa, List<Etapa> listEtapas)
    {
        consultaNome.setText(pessoa.getNome());
        consultaSobrenome.setText(pessoa.getSobrenome());
        
        consultaSala1Parte.setText("Nenhuma sala disponível/cadastrada!");
        consultaEspaco1Parte.setText("Nenhum espaço café disponível/cadastrado!");
        consultaSala2Parte.setText("Nenhuma sala disponível/cadastrada!");
        consultaEspaco2Parte.setText("Nenhum espaço café disponível/cadastrado!");
        
        for (Etapa etapa : listEtapas) {
            if (etapa.getTipoEtapa().getId() == 1)
            {
                if (etapa.getEspaco().getTipoEspaco().getId() == 1)
                {
                    consultaSala1Parte.setText(etapa.getEspaco().getNome());
                }
                else if (etapa.getEspaco().getTipoEspaco().getId() == 2)
                {
                    consultaEspaco1Parte.setText(etapa.getEspaco().getNome());
                }
            }
            else
            {
                if (etapa.getEspaco().getTipoEspaco().getId() == 1)
                {
                    consultaSala2Parte.setText(etapa.getEspaco().getNome());
                }
                else if (etapa.getEspaco().getTipoEspaco().getId() == 2)
                {
                    consultaEspaco2Parte.setText(etapa.getEspaco().getNome());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        consultaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consultaSobrenome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        consultaSala1Parte = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        consultaEspaco1Parte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        consultaSala2Parte = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        consultaEspaco2Parte = new javax.swing.JTextField();
        consultaFechar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consulta de pessoas");
        setPreferredSize(new java.awt.Dimension(400, 485));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Detalhes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        consultaNome.setEditable(false);
        getContentPane().add(consultaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 320, -1));

        tabelaPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPessoas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaPessoas);
        if (tabelaPessoas.getColumnModel().getColumnCount() > 0) {
            tabelaPessoas.getColumnModel().getColumn(0).setResizable(false);
            tabelaPessoas.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 370, 100));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 400, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Consulta de pessoas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel4.setText("Sobrenome");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        consultaSobrenome.setEditable(false);
        getContentPane().add(consultaSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 290, -1));

        jLabel5.setText("Sala de evento - 1ª parte");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        consultaSala1Parte.setEditable(false);
        getContentPane().add(consultaSala1Parte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 230, -1));

        jLabel6.setText("Espaço café - 1ª parte");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        consultaEspaco1Parte.setEditable(false);
        getContentPane().add(consultaEspaco1Parte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 240, -1));

        jLabel7.setText("Sala de evento - 2ª parte");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        consultaSala2Parte.setEditable(false);
        getContentPane().add(consultaSala2Parte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 230, -1));

        jLabel8.setText("Espaço café - 2ª parte");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        consultaEspaco2Parte.setEditable(false);
        getContentPane().add(consultaEspaco2Parte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 240, -1));

        consultaFechar.setText("Fechar");
        consultaFechar.setActionCommand("Cancelar");
        getContentPane().add(consultaFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 370, -1));

        jLabel9.setText("Para visualizar os detalhes clique sobre o nome da pessoa");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consultaEspaco1Parte;
    private javax.swing.JTextField consultaEspaco2Parte;
    private javax.swing.JButton consultaFechar;
    private javax.swing.JTextField consultaNome;
    private javax.swing.JTextField consultaSala1Parte;
    private javax.swing.JTextField consultaSala2Parte;
    private javax.swing.JTextField consultaSobrenome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaPessoas;
    // End of variables declaration//GEN-END:variables
}
