package view;

import controller.SalaEventoController;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.entity.Espaco;
import model.entity.Etapa;

public class JInternalFrameConsultaSalaEvento extends javax.swing.JInternalFrame {

    private final SalaEventoController salaEventoController;
    
    private List<Espaco> listSalaEvento;
    
    public JInternalFrameConsultaSalaEvento() {
        initComponents();
        
        salaEventoController = new SalaEventoController(this);
        
        consultaFechar.addActionListener(salaEventoController);
        
        tabelaSalaEvento.getSelectionModel().addListSelectionListener(salaEventoController);
    }
    
    public JTable getTable()
    {
        return tabelaSalaEvento;
    }
    
    public void setListSalaEvento(List<Espaco> listSalaEvento)
    {
        this.listSalaEvento = listSalaEvento;
        
        DefaultTableModel dtm = (DefaultTableModel) tabelaSalaEvento.getModel();
        dtm.setRowCount(0);
        
        for (Espaco espaco : this.listSalaEvento)
        {
            Object[] objEspaco = {espaco.getNome(), espaco.getLotacao()};
            dtm.addRow(objEspaco);
        }
    }
    
    public Espaco getSalaSelecionada(int selected)
    {
        return listSalaEvento.get(selected);
    }
    
    public void setSalaSelecionada(List<Etapa> listEtapa)
    {
        DefaultTableModel dtm1 = (DefaultTableModel) tabelaEtapa1.getModel();
        dtm1.setRowCount(0);
        
        DefaultTableModel dtm2 = (DefaultTableModel) tabelaEtapa2.getModel();
        dtm2.setRowCount(0);
        
        for (Etapa etapa : listEtapa)
        {
            Object[] objPessoa = {etapa.getPessoa().getNome(), etapa.getPessoa().getSobrenome()};
            
            if (etapa.getTipoEtapa().getId() == 1)
            {
                dtm1.addRow(objPessoa);
            }
            else
            {
                dtm2.addRow(objPessoa);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaSalaEvento = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        consultaFechar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaEtapa1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaEtapa2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consulta de sala de evento");
        setPreferredSize(new java.awt.Dimension(702, 487));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Consulta de sala de evento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        tabelaSalaEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Lotação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaSalaEvento.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaSalaEvento);
        if (tabelaSalaEvento.getColumnModel().getColumnCount() > 0) {
            tabelaSalaEvento.getColumnModel().getColumn(0).setResizable(false);
            tabelaSalaEvento.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 660, 120));

        jLabel9.setText("Para visualizar os detalhes clique sobre o nome da sala");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 10));

        consultaFechar.setText("Fechar");
        consultaFechar.setActionCommand("Cancelar");
        getContentPane().add(consultaFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 660, -1));

        tabelaEtapa1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEtapa1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaEtapa1);
        if (tabelaEtapa1.getColumnModel().getColumnCount() > 0) {
            tabelaEtapa1.getColumnModel().getColumn(0).setResizable(false);
            tabelaEtapa1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 310, 170));

        jLabel1.setText("Participantes na Etapa 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        tabelaEtapa2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaEtapa2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaEtapa2);
        if (tabelaEtapa2.getColumnModel().getColumnCount() > 0) {
            tabelaEtapa2.getColumnModel().getColumn(0).setResizable(false);
            tabelaEtapa2.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 310, 170));

        jLabel2.setText("Participantes na Etapa 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultaFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaEtapa1;
    private javax.swing.JTable tabelaEtapa2;
    private javax.swing.JTable tabelaSalaEvento;
    // End of variables declaration//GEN-END:variables
}
